### ISSUE TITLE
Pass request params as props to top level component

### ISSUE THREAD

**Issue by jordwalke** [facebookarchive/react-page#14]
```
http://localhost:8080/index.html?me=person
```

Should allow the top level component that is routed to, to be able to read `this.props.me`.

**Comment by shaneosullivan** [comment]
Can you make it so that only declared public props get passed in, so that
its not possible to shove any bad data into the component just by modifying
the URL?

**Comment by jordwalke** [comment]
@shaneosullivan: Maybe if we don't just blindly clobber props, and instead allow the top level component to access them via `this.props.requestParams` - that could help eliminate giving URLs more control than intended.
