### ISSUE TITLE
I don't understand the output of node server.js

### ISSUE THREAD

**Issue by vjeux** [facebookarchive/react-page#17]
Is this output a bug or a feature? (Note: I included several different terminal width to make sure it wasn't because of its size)

![colors](https://f.cloud.github.com/assets/197597/1064488/19c424d0-1335-11e3-90cd-9092102bb87e.png)

**Comment by jordwalke** [comment]
It is supposed to output timing bar charts that span the current width of your terminal. It doesn't dynamically resize previous logs as you resize your window, but should always output according to the current width.

Are you seeing anything different?

**Comment by vjeux** [comment]
Oh I see, this is very weird that the text is being cropped. It looks like it is broken rather than intended.

## 

Christopher "vjeux" Chedeau
Facebook Engineer
http://blog.vjeux.com/

**Comment by jordwalke** [comment]
Oh, yeah - if the screen width is too small, the text is cropped. Expand the terminal until you can read it. Also, if you remember what each position represents, then you can just know that too small to read === too small to care about :)
