### ISSUE TITLE
Small Question About Using Other Node Modules

### ISSUE THREAD

**Issue by lyaunzbe** [facebookarchive/react-page#2]
Hello! This is really great so far, definitely an improvement over reactapp. Just one small thing: How would I use other modules I have npm installed in my React components? It seems like react-middleware might not be bundling any of my other node modules besides React, or I may be missing something else more obvious? Thanks for all your help. Cheers :+1:

**Comment by jordwalke** [comment]
There is an explicit whitelist that you must add your components to. I'm revisiting this decision right now. But if you expect `react-page` to automatically bundle browser implementations of things like `require('util')`, then I'll also have to add support for that (done now - testing in process).

**Comment by lyaunzbe** [comment]
Node modules work now (mostly) and browser implementations of native node modules has been added.
