### ISSUE TITLE
Cannot switch top level component type.

### ISSUE THREAD

**Issue by jordwalke** [facebookarchive/react-page#20]
We should document the limitation here, and possibly fix this in the react core. When the top level component type switches, we can't innerHTML the entire document, so we might need to special case it. Thanks to @andreypopp for finding this one.

**Comment by petehunt** [comment]
Related to this, if you mess up and the server rendered checksum doesn't match you'll also have this issue.

**Comment by andreypopp** [comment]
I think this can be closed cause React now has a special code path for mutating `<html>` element.

**Comment by petehunt** [comment]
Fixed in https://github.com/facebook/react/commit/c8886a0424c426818566c21d5a69c4cb8f5d41e3
