### ISSUE TITLE
Broken by React change

### ISSUE THREAD

**Issue by kassens** [facebookarchive/react-page#21]
Since facebook/react@647731e399fc824c02fdf851d91ce4477958e7fe loading a fresh checkout gives me:

```
Uncaught Error: Invariant Violation: prepareEnvironmentForDOM(...): Target container is not a DOM element.
```

**Comment by jordwalke** [comment]
I committed a temporary hack/fix. If you reclone it should work now - but that needs to be fixed in the react core (that and the global **VERSION** that fails (temporarily fixed that one too). Feel free to fix the bug @kassens.

**Comment by jordwalke** [comment]
Should be fixed - hopefully someone fixes the core react issue.
