### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by shaneosullivan** [facebookarchive/react-page#22]
On a new machine, with the latest Node and NPM, doing npm install gives the error below.  It seems strange that it would complain about Xcode.

Also, apparently react-tools should be installed globally.  Is this really required?  I want to put this on my web server, and would rather not muck about with folders that require root access.

npm http 304 https://registry.npmjs.org/amdefine
xcode-select: Error: No Xcode is selected. Use xcode-select -switch <path-to-xcode>, or see the xcode-select manpage (man xcode-select) for further information.

gyp: Error 2 running xcodebuild
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:424:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Darwin 12.4.1
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/shaneos/Dev/react-page/node_modules/react-page-middleware/node_modules/contextify
gyp ERR! node -v v0.10.18
gyp ERR! node-gyp -v v0.10.9
gyp ERR! not ok 
npm http 304 https://registry.npmjs.org/esprima-fb/1001.1001.1000-dev-harmony-fb
npm ERR! Error: ENOENT, open '/Users/shaneos/Dev/react-page/node_modules/react-page-middleware/node_modules/node-haste/node_modules/esprima-fb/.npmignore'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Darwin 12.4.1
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/shaneos/Dev/react-page
npm ERR! node -v v0.10.18
npm ERR! npm -v 1.3.8
npm ERR! path /Users/shaneos/Dev/react-page/node_modules/react-page-middleware/node_modules/node-haste/node_modules/esprima-fb/.npmignore
npm ERR! code ENOENT
npm ERR! errno 34

**Comment by zpao** [comment]
[contextify](https://github.com/brianmcd/contextify) is a binary package and has a build step which requires building against v8, so that's why that happened.

As for the "global" react-tools, that's perfectly safe to ignore. I set that up since the main draw of the package (at least initially) was for the `jsx` executable. No global install is actually required.

**Comment by jordwalke** [comment]
We should make contextify optional - if you have xcode we can install contextify and run the server rendering in a sandbox, otherwise we can just eval it in the standard context, which won't have the same security protections obviously.

**Comment by kassens** [comment]
Is require('vm') not enough?

```
—
```

**Comment by jordwalke** [comment]
I just recently remove the dependency on contextify so this shouldn't happen any more.

**Comment by kassens** [comment]
Reopen when you still see this, looks like this ticket is out of date.
