### ISSUE TITLE
Only index route is working

### ISSUE THREAD

**Issue by daslicht** [facebookarchive/react-page#31]
only displaying the index is working, all other routes fail?

**Comment by jordwalke** [comment]
Did you try:

```
http://localhost:8080/pages/about.html
```

Here's how the current router works.
- Take the url
- Replace `html` with `.js`
- If no `.html` extension, search for `index.js` in that directory.

Are you seeing something different? BTW: You can also inject a custom router by hacking `servers.js`. If you have a better router in mind, feel free to send a pull request.

**Comment by jordwalke** [comment]
Let me know if it is still an issue.
