### ISSUE TITLE
500 Error: Syntax Error: /home/[..]/react-page/src/index.js TypeError: Object #<Object> has no method 'traverse'

### ISSUE THREAD

**Issue by xelius** [facebookarchive/react-page#39]
Good people!
 I'm getting the below error upon doing a clean git clone and npm install. Not sure if this is a bug or just me doing something stupid. I'm running node 0.10.21 on ubuntu 13.10.

"500 Error: Syntax Error: /home/henke/annat/react-page/src/index.js TypeError: Object #<Object> has no method 'traverse'
at transformModuleImpl (/home/henke/annat/react-page/node_modules/react-page-middleware/src/Packager.js:221:7)
at /home/henke/annat/react-page/node_modules/react-page-middleware/src/Packager.js:245:9
at fs.js:266:14
at Object.oncomplete (fs.js:107:15)"

Any thoughts?

Thanks a lot.

**Comment by jordwalke** [comment]
Taking a look. This appears to be a new error - likely one of our dependencies.

**Comment by jordwalke** [comment]
I think this is a problem with master React - someone is getting a fix. Thanks for reporting.

**Comment by zpao** [comment]
https://github.com/facebook/react/commit/b2507066b610e0316d7a4a4d62685c58b3a34629 should fix this.

**Comment by jordwalke** [comment]
Reclone and rerun `npm install`. Thanks!

**Comment by xelius** [comment]
Awesome, works like a charm.
You guys are quick!
