### ISSUE TITLE
Missing attributes for <meta>

### ISSUE THREAD

**Issue by vjeux** [facebookarchive/react-page#41]
Input:

```
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
<meta property="og:type" content="website" />
```

Output:

```
<meta />
<meta content="IE=edge,chrome=1" />
<meta content="website" />
```

Missing:
- charset
- http-equiv
- property

**Comment by vjeux** [comment]
@zpao rightly pointed me at the fact that - should be camelCased.
- httpEquiv
- charSet

Now there's still the issue that property is non-standard

**Comment by vjeux** [comment]
Suggested fix, add `property` in the list of non-standard properties

https://github.com/facebook/react/blob/master/src/dom/DefaultDOMPropertyConfig.js#L114

**Comment by vjeux** [comment]
https://github.com/facebook/react/issues/655

**Comment by RavenHursT** [comment]
@vjeux came across this today.. curious.. why does `charSet` _have_ to be camelCase?  

https://github.com/facebook/react/blob/master/src/dom/DefaultDOMPropertyConfig.js#L114 is 404'ing so no info found there.

I came across this because I was trying to do something like the following in a `HeadTag` component:

```
renderMetaTag(attribs, index) {
  return (
    <meta key={index} {...attribs} />
  )
}

render(){
  return (
    <head>
      {this.props.metaTags && this.props.metaTags.map(this.renderMetaTag)}
    </head>
  )
}
```

Seems odd to me as to why the plain HTML attribute names aren't just passed through and outputted onto the generated element?

**Comment by vjeux** [comment]
I'm not really sure what is going on but it works with charSet and not charset :p 

https://github.com/facebook/react/blob/308badbc03dec458faccad599baf618eacb77c9b/src/renderers/dom/shared/HTMLDOMPropertyConfig.js#L48

My guess is that the javascript setter for the property is charSet and not charset. Same reason we have className and not class

**Comment by RavenHursT** [comment]
That's so odd... seems simple enough to define the object like so: 

```
{
  'char-set': null,
  'http-equiv': null,
  .
  .
  .
  etc
}
```

Would definitely remove a lot of confusion here....

**Comment by zpao** [comment]
React has been like this forever to align more with JS APIs. We have no intention to change at this point.

**Comment by RavenHursT** [comment]
Well.. that's unfortunate..

**Comment by royalicing** [comment]
Any chance that React (maybe just ReactDOM/server) could warn with invalid use of `charset` and `http-equiv`?
