### ISSUE TITLE
Homepage: Staggered scrolling while cursor over code block

### ISSUE THREAD

**Issue by sudochop** [facebookarchive/react-page#45]
OS X 10.9 - When cursor is over a code block, doing a gestural scroll causes choppy movement.

**Comment by jordwalke** [comment]
I'll close this for now, because I don't understand how it relates to `react-page`. Please feel free to clarify.

**Comment by andreypopp** [comment]
I think it's related to http://facebook.github.io/react

**Comment by sudochop** [comment]
@andreypopp Correct

**Comment by jordwalke** [comment]
I see.

**Comment by zpao** [comment]
Did an issue ever get opened against https://github.com/facebook/react? If not, can you create one with as much detail as possible (browser, etc)

**Comment by sudochop** [comment]
https://github.com/facebook/react/issues/678
