### ISSUE TITLE
Remove react-styles dependency

### ISSUE THREAD

**Issue by kassens** [facebookarchive/react-page#49]
I think it would be good if the basic react-page example would be more minimal and not rely on additional proprietary code. Additions such as react-styles add complexity that users have to understand at the same time they're trying to understand React itself.
I think a better place to demonstrate add-ons would be in separate sub-pages or branches.

**Comment by jordwalke** [comment]
Good idea @kassens. Feel free to move the `react-style` usage to a separate branch or fork. I really like `react-style` though, but it's good to show that it's not needed to use `React/react-page`
