### ISSUE TITLE
Diverged dependencies (error on startup)

### ISSUE THREAD

**Issue by parris** [facebookarchive/react-page#51]
Running node 0.10.24

I'm getting the following error:
    > node server.js

```
/Users/parris/Projects/react-page/node_modules/react-page-middleware/src/Packager.js:36
 reactVisitors = require('react-tools/vendor/fbtransform/visitors').getVisitor
                                                                ^
TypeError: Object #<Object> has no method 'getVisitorsList'
```

I am guessing react-tools has diverged from react-page. 

I would comment on those projects; however, I noticed that the tools are just being hosted through git. Perhaps those git repos should be replaced with the npm packages or have a specific git tag associated with them.

**Comment by jordwalke** [comment]
Right now, react-page (and react-page-middleware) just point to master react-tools. We could/should just lock in a version in the package.json. You can try cleaning out the node_modules and picking the last stable version of React in the git url. Feel free to send a pull request.

**Comment by zpao** [comment]
Should be working now with the latest updates (might need to `rm -rf node_modules`) thanks to @dhl in https://github.com/facebook/react-page-middleware/pull/17
