### ISSUE TITLE
Uncaught Error on localhost  (local machine)

### ISSUE THREAD

**Issue by svagi** [facebookarchive/react-page#57]
I have trouble running clean react-page clone on local machine. It always throws this exception in client chrome console:

`Uncaught Error Requiring unknown module "es5-shim/es5-shim.js" 
E:\react-page\node_modules\react-page-middleware\polyfill\require.js:187`

On server runs everything ok.

**Comment by jordwalke** [comment]
What operating system are you using?

**Comment by svagi** [comment]
Windows 8.1

**Comment by jordwalke** [comment]
`react-page` has basic support OSX and Linux (it mentions on the README). I'd love if someone would get windows 8.1 support working. There may be some stuff that incorrectly depends on a particular file system path formatting, instead of using `require('path')`. Feel free to dig in.

**Comment by svagi** [comment]
Oh, I did't notice. Well, I searched a bit and one solution might be not to use `es5-shim`. You can then run react-page on Windows just fine (sure, without `es5-shim` functionality).

**Comment by jordwalke** [comment]
Really? I know we had some server issues with Windows, but it looks like those may have been fixed! That's great, now I can get a sweet MS Surface :)
Can you figure out why `es5-shim` is failing on windows?
